[project]
name = "pie-stream"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flake8"
]

[project.scripts]
lint = "flake8"

[dependency-groups]
dev = [
    "flake8>=7.3.0",
]
